// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzFx2R3F2_pUq6JVVK8VOb67c7gmn_iI',
    appId: '1:168134864112:web:c5f3688f0419ad56296635',
    messagingSenderId: '168134864112',
    projectId: 'zeus-384017',
    authDomain: 'zeus-384017.firebaseapp.com',
    storageBucket: 'zeus-384017.appspot.com',
    measurementId: 'G-2F4VPHTM7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6GzLDssfMuj4F-rGM3dvGb4b9mW0_dGU',
    appId: '1:168134864112:android:23210cc0076a508a296635',
    messagingSenderId: '168134864112',
    projectId: 'zeus-384017',
    storageBucket: 'zeus-384017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23F7kqN7yaYFmw5D5TeX7i7vBC7twb-g',
    appId: '1:168134864112:ios:5d55036eac3bd73a296635',
    messagingSenderId: '168134864112',
    projectId: 'zeus-384017',
    storageBucket: 'zeus-384017.appspot.com',
    iosClientId: '168134864112-pbn2p35m0ekp5e8j5clbgbifi4efrsqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.stories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD23F7kqN7yaYFmw5D5TeX7i7vBC7twb-g',
    appId: '1:168134864112:ios:eb2bd9a8f43dde59296635',
    messagingSenderId: '168134864112',
    projectId: 'zeus-384017',
    storageBucket: 'zeus-384017.appspot.com',
    iosClientId: '168134864112-vlcni0nlo5408kvbguk65t8nfd11455a.apps.googleusercontent.com',
    iosBundleId: 'com.example.stories.RunnerTests',
  );
}
